name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true
        
    - name: publish
      run: 
        dotnet publish -c release
      
    - name: Change base-tag in index.html from / to the necessary
      run: sed -i 's/<base href="\/" \/>/<base href="\/NecromundaDiceRoller-Blazor\/" \/>/g' ./bin/release/net8.0/publish/wwwroot/index.html

    - name: add imports
      run: sed -i '<link href="_content\/MatBlazor\/dist\/matBlazor.css" rel="stylesheet"\ /> <script src="_content\/MatBlazor\/dist\/matBlazor.js"><\/script>' ./bin/release/net8.0/publish/wwwroot/index.html
      
    - name: Add .nojekyll file
      run: touch ./bin/release/net8.0/publish/wwwroot/.nojekyll
      
    - uses: JamesIves/github-pages-deploy-action@3.7.1
      name: gh-pages publish
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: ./bin/release/net8.0/publish/wwwroot
